import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { PrivyProvider } from "@/providers/privy-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="font-sans">
      <body className="antialiased">
        <PrivyProvider>
          <div className="min-h-screen w-full relative bg-white overflow-hidden">

            {/* Cool Blue Glow Top */}
            <div
              className="absolute inset-0 z-0"
              style={{
                background: "#ffffff",
                backgroundImage: `
                  radial-gradient(
                    circle at top center,
                    rgba(0, 132, 255, 0.45),
                    transparent 70%
                  )
                `,
                filter: "blur(80px)",
                backgroundRepeat: "no-repeat",
              }}
            />

            {/* Content Layer */}
            <div className="relative z-10">
              <Navbar />
              {children}
            </div>

          </div>
        </PrivyProvider>
      </body>
    </html>
  );
}