import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Instrument_Serif, Playfair_Display } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Navbar } from "@/components/Navbar";
import { PrivyProvider } from "@/providers/privy-provider";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const instrumentSerif = Instrument_Serif({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-instrument-serif",
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair-display",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn(
        "font-sans",
        inter.variable,
        instrumentSerif.variable,
        playfairDisplay.variable
      )}
    >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <PrivyProvider>
          <div className="min-h-screen w-full relative bg-white overflow-hidden">

            {/* Cool Blue Glow Top */}
            <div
              className="absolute inset-0 z-0"
              style={{
                background: "#ffffff",
                backgroundImage: `
                  radial-gradient(
                    circle at top center,
                    rgba(0, 132, 255, 0.45),
                    transparent 70%
                  )
                `,
                filter: "blur(80px)",
                backgroundRepeat: "no-repeat",
              }}
            />

            {/* Content Layer */}
            <div className="relative z-10">
              <Navbar />
              {children}
            </div>

          </div>
        </PrivyProvider>
      </body>
    </html>
  );
}